### ISSUE TITLE
simple-peer on sveltekit (uses Vite behind the scene)

### ISSUE THREAD

**Issue by pjebs** [browserify/randombytes#30] opened 2022-04-08 01:30 UTC
It seems like this package is creating some issues with sveltekit (uses Vite behind the scene)
```
global is not defined
ReferenceError: global is not defined
    at node_modules/randombytes/browser.js (http://localhost:3000/node_modules/.vite/simple-peer.js?v=10be15c3:2351:18)
    at __require (http://localhost:3000/node_modules/.vite/chunk-UNANNA3Z.js?v=10be15c3:38:50)
    at node_modules/simple-peer/index.js (http://localhost:3000/node_modules/.vite/simple-peer.js?v=10be15c3:5160:23)
    at __require (http://localhost:3000/node_modules/.vite/chunk-UNANNA3Z.js?v=10be15c3:38:50)
    at http://localhost:3000/node_modules/.vite/simple-peer.js?v=10be15c3:6017:27
```

**Comment by ErcouldnT** [comment] 2022-05-10 22:34
Any solution for this?

**Comment by Dr-Chaos** [comment] 2022-05-24 22:00
I use Vite too (with Vuejs)  and have the same issue :/

**Comment by daroOkpeku** [comment] 2022-10-17 11:24
I am have the same issue on react

**Comment by dcousens** [comment] 2023-07-26 07:15
Probably a duplicate of https://github.com/browserify/randombytes/issues/33

**Closed by dcousens** 2023-07-26 07:15 UTC
